version: '3'

services:
 nagios:
  environment:
   NAGIOS_TIMEZONE: 'America/New_York'
   NAGIOS_FQDN: 'nagios.lan.chtm.me'
  image: jasonrivers/nagios:latest
  volumes:
   - nagiosetc:/opt/nagios/etc
   - nagiosvar:/opt/nagios/var
   - customplugins:/opt/Custom-Nagios-Plugins
   - nagiosgraphvar:/opt/nagiosgraph/var
   - nagiosgraphetc:/opt/nagiosgraph/etc
  
volumes:
  nagiosetc:
  nagiosvar:
  customplugins:
  nagiosgraphvar:
  nagiosgraphetc: